language: ruby
rvm:
- 1.9.3
- 2.1.1
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: fccKfNOKwv/CErzezggpOGhnZ1Cz/B8EL8jp6kBilfDKsyoL+gzmp+Z187feLQlJpVmV/JS3beGGC47Ih61FwmxlsPFv19hQuMp8K5AXuJCUQc8RqdaSl6FP0FbeqWjNgzm2HxgBukvJpyX/2XhtzREvTXKRcTu5vF6IkahJN8U=
  gem: swagger_roar
  on:
    repo: ytaras/swagger_roar
